# proj parameters
RUN_ID: "Round1_hg19" # "RUN_id"
THREADS: 5
# multibam
binsize: "50000"
#correlation
corplot: heatmap
method: pearson
Acetylation: 'H3K27ac'
Methylation: 'H3K36me3'
Polycomb: 'H3K27me3'
#Cut&Tag or ChIP
c_t: 'Cut-Tag'
chip: 'ChIP'
chip-se: 'ChIP-SE'
tag: 'Tag'
#index Bowtie2
index_bt2_hg: "/home/mattia/Genomes/hg38/fa/hg38"
chrom_size: "/home/mattia/Genomes/hg19/hg19.chrom.sizes"
#downsample target
target_reads: "5000000"
# peaks
genome_size_bp: 2730871774
peaks_qvalue: 0.01
#Coverage
binsize: "10"
norm_method: "RPKM"
smooth_length: "300"
# Path to a JSON file with samples and their corresponding FASTQ files.
SAMPLES: './snakemake/SRR.txt'
SAMPLES_JSON: './snakemake/samples_tagAlign.json'
