# proj parameters
RUN_ID: "S3_nanoCT" # "RUN_id"
THREADS: 5
# trimming
adapters: "/home/mattia/Trimmomatic/adapters/Neb_Next_s3.fa"
# peaks
genome_size_bp: 2730871774
peaks_qvalue: 0.01
#Coverage
binsize: "10"
norm_method: "RPKM"
smooth_length: "300"
#Cut&Tag or ChIP
c_t: 'nanoCT'
chip: 'ChIP'
Acetylation: 'H3K27ac'
Methylation: 'H3K36me3'
Polycomb: 'H3K27me3'
#index Bowtie2
index_bt2_hg: "/home/mattia/Genomes/hg38/fa/hg38"
#downsample target
target_reads: "5000000"
# Path to a JSON file with samples and their corresponding FASTQ files.
SAMPLES: '/home/mattia/cfChromatin_in_MS/snakemake/SRR.txt'
SAMPLES_JSON: '/home/mattia/cfChromatin_in_MS/snakemake/samples_nanoCT_S3.json'
